name: on-on release-publish-to-npm
on:
  release:
    types: [created]
jobs:
  publish:
    if: github.repository_owner == 'adobe'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
          access: "public"
        env: # More info about the environment variables in the README
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
          NPM_AUTH: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
